export const coursesData = [
  {
    id: 1,
    name: "Introduction to Programming",
    code: "CS101",
    instructor: "Dr. Smith",
    semester: "1st",
  },
  {
    id: 2,
    name: "Data Structures",
    code: "CS102",
    instructor: "Dr. John",
    semester: "2nd",
  },
  {
    id: 3,
    name: "Algorithms",
    code: "CS103",
    instructor: "Dr. Anna",
    semester: "3rd",
  },
  {
    id: 4,
    name: "Operating Systems",
    code: "CS201",
    instructor: "Dr. Lee",
    semester: "4th",
  },
  {
    id: 5,
    name: "Database Systems",
    code: "CS202",
    instructor: "Dr. Clark",
    semester: "5th",
  },
  {
    id: 6,
    name: "Software Engineering",
    code: "CS301",
    instructor: "Dr. Baker",
    semester: "6th",
  },
  {
    id: 7,
    name: "Computer Networks",
    code: "CS302",
    instructor: "Dr. Miles",
    semester: "7th",
  },
  {
    id: 8,
    name: "Machine Learning",
    code: "CS401",
    instructor: "Dr. Williams",
    semester: "8th",
  },
  {
    id: 9,
    name: "Ethics in Computing",
    code: "CS104",
    instructor: "Dr. O'Neil",
    semester: "1st",
  },
  {
    id: 10,
    name: "Digital Logic Design",
    code: "EE101",
    instructor: "Dr. Logan",
    semester: "2nd",
  },
  {
    id: 11,
    name: "Physics",
    code: "PH201",
    instructor: "Dr. Paterson",
    semester: "3rd",
  },
];
